
</section>

<div class="footer">

<script type="text/javascript" src="<?php echo $js; ?>popper.min.js"></script>
<script type="text/javascript" src="<?php echo $js; ?>jquery-3.4.1.min.js"></script>
<script type="text/javascript" src="<?php echo $js; ?>jquery-ui.min.js"></script>
<script type="text/javascript" src="<?php echo $js; ?>bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo $js; ?>jquery.selectBoxIt.min.js"></script>
<script type="text/javascript" src="<?php echo $js; ?>AJAX.js"></script>
<script type="text/javascript" src="<?php echo $js; ?>js.js"></script>

</div>

</body>
</html>
